# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("ne_CV_RE", "ne_CV_noRE", "ne_noCV_RE", "ne_noCV_noRE", "w_CV_RE", "w_CV_noRE", "w_noCV_RE", "w_noCV_noRE", "w_sim_best_model", "w_sim_over_time")

# load each stan module
Rcpp::loadModule("stan_fit4ne_CV_RE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ne_CV_noRE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ne_noCV_RE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ne_noCV_noRE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4w_CV_RE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4w_CV_noRE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4w_noCV_RE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4w_noCV_noRE_mod", what = TRUE)
Rcpp::loadModule("stan_fit4w_sim_best_model_mod", what = TRUE)
Rcpp::loadModule("stan_fit4w_sim_over_time_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
